import React, { useState, useEffect } from 'react';

export default function BioAgentsGovernance() {

  // Auto-wired API Data State
  const [liveData, setLiveData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Verify backend connectivity
    fetch('http://127.0.0.1:8000/api/health')
      .then(res => res.json())
      .then(data => {
        setLiveData([data]);
        setIsLoading(false);
      })
      .catch(err => {
        console.error("Backend Disconnected:", err);
        setIsLoading(false);
      });
  }, []);

  return (
    <div className="min-h-screen bg-[#050505] text-slate-300 font-mono p-8">
      
      <div className="max-w-5xl mx-auto">
        
        <header className="mb-10 border-b border-slate-800 pb-6 flex justify-between items-end">
          <div>
            <h1 className="text-2xl font-bold text-white tracking-wider flex items-center gap-3 uppercase">
               <span className="text-rose-500">🛡️</span> Governance & Human Review
            </h1>
            <p className="text-slate-500 mt-2 text-sm font-sans max-w-3xl">
               Human-in-the-loop interventions. Critical agent actions (e.g., medical diagnoses, clinical trial design, public health alerts) are paused here for manual expert approval before execution or publication.
            </p>
          </div>
          <div className="bg-rose-900/30 text-rose-500 border border-rose-800 px-4 py-2 rounded text-sm font-bold flex items-center gap-2">
             <div className="w-2 h-2 bg-rose-500 rounded-full animate-ping"></div>
             2 Pending Approvals
          </div>
        </header>

        <div className="space-y-6">
           
           {/* Governance Item 1 */}
           <div className="bg-[#111] border border-rose-900/50 rounded-xl overflow-hidden shadow-[0_0_15px_rgba(225,29,72,0.1)]">
              <div className="bg-rose-950/20 px-6 py-3 border-b border-rose-900/50 flex justify-between items-center">
                 <div className="flex items-center gap-3">
                    <span className="px-2 py-0.5 bg-rose-900 text-rose-300 text-[10px] font-bold uppercase rounded">High Risk</span>
                    <span className="text-sm font-bold text-white font-sans">Clinical Protocol Generation</span>
                 </div>
                 <span className="text-xs text-slate-500">Generated by: ClinicalAgent</span>
              </div>
              
              <div className="p-6">
                 <p className="text-sm font-sans text-slate-300 mb-4">
                    The ClinicalAgent has generated a phase I trial protocol for repurposed compound XZ-204 in pregnant patients with TNBC. 
                    <br/><br/>
                    <strong className="text-rose-400">Governance Flag:</strong> Inclusion of vulnerable populations (pregnancy) requires mandatory human ethics board review prior to finalization.
                 </p>
                 
                 <div className="bg-[#050505] p-4 border border-slate-800 rounded text-xs text-slate-400 mb-6 font-sans">
                    <strong>Excerpt:</strong> "...inclusion criteria encompasses patients in the second and third trimester..."
                 </div>

                 <div className="flex gap-4">
                    <button className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-bold rounded transition">
                       Approve & Continue
                    </button>
                    <button className="px-4 py-2 bg-[#050505] border border-rose-900 text-rose-500 hover:bg-rose-950 text-sm font-bold rounded transition">
                       Reject & Request Revision
                    </button>
                 </div>
              </div>
           </div>

           {/* Governance Item 2 */}
           <div className="bg-[#111] border border-amber-900/50 rounded-xl overflow-hidden shadow-[0_0_15px_rgba(217,119,6,0.05)]">
              <div className="bg-amber-950/20 px-6 py-3 border-b border-amber-900/50 flex justify-between items-center">
                 <div className="flex items-center gap-3">
                    <span className="px-2 py-0.5 bg-amber-900 text-amber-300 text-[10px] font-bold uppercase rounded">Medium Risk</span>
                    <span className="text-sm font-bold text-white font-sans">Public Health Data Export</span>
                 </div>
                 <span className="text-xs text-slate-500">Generated by: PublicHealthAgent</span>
              </div>
              
              <div className="p-6">
                 <p className="text-sm font-sans text-slate-300 mb-4">
                    PublicHealthAgent is attempting to export an epidemiological dataset concerning regional outbreak vectors.
                    <br/><br/>
                    <strong className="text-amber-400">Governance Flag:</strong> Data contains high-resolution geolocation tags which may violate PII/HIPAA de-identification standards. Human review requested to confirm spatial blurring is adequate.
                 </p>

                 <div className="flex gap-4 mt-6">
                    <button className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-bold rounded transition">
                       Approve Export
                    </button>
                    <button className="px-4 py-2 bg-[#050505] border border-amber-900 text-amber-500 hover:bg-amber-950 text-sm font-bold rounded transition">
                       Halt & Anonymize Data
                    </button>
                 </div>
              </div>
           </div>

        </div>

      </div>
    </div>
  );
}
