import React, { useState, useEffect } from 'react';

export default function BioReasonEvidence() {

  // Auto-wired API Data State
  const [liveData, setLiveData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Verify backend connectivity
    fetch('http://127.0.0.1:8000/api/health')
      .then(res => res.json())
      .then(data => {
        setLiveData([data]);
        setIsLoading(false);
      })
      .catch(err => {
        console.error("Backend Disconnected:", err);
        setIsLoading(false);
      });
  }, []);

  return (
    <div className="min-h-screen bg-[#050505] text-slate-300 font-mono p-8">
      
      <div className="max-w-6xl mx-auto">
        
        <header className="mb-10">
          <h1 className="text-2xl font-bold text-white tracking-wider flex items-center gap-3 uppercase">
             <span className="text-emerald-500">📑</span> Evidence Aggregation & Provenance
          </h1>
          <p className="text-slate-500 mt-2 text-sm font-sans max-w-3xl">
             Every claim generated by BioReason is explicitly mapped to its underlying citations. This dashboard visualizes the evidence trail.
          </p>
        </header>

        <div className="bg-[#0a0a0a] border border-slate-800 rounded-xl p-8 shadow-2xl">
           
           {/* Synthesized Claim */}
           <div className="mb-10">
              <h3 className="text-xs text-slate-500 font-bold uppercase tracking-widest mb-3">Synthesized Claim</h3>
              <div className="p-5 bg-[#111] border-l-4 border-emerald-500 rounded text-lg font-sans text-slate-200">
                 "Inhibition of the Wnt/beta-catenin pathway in APC-mutant colorectal cancer induces apoptosis primarily through the secondary alteration of the Bax/Bcl-2 ratio, rather than a direct, immediate induction of caspase cascades."
              </div>
           </div>

           <h3 className="text-xs text-slate-500 font-bold uppercase tracking-widest mb-4">Evidence Trail (Provenance)</h3>
           
           <div className="space-y-4">
              
              {/* Evidence 1 */}
              <div className="bg-[#111] border border-slate-800 p-5 rounded-lg flex gap-4">
                 <div className="w-12 h-12 bg-emerald-950/30 rounded flex items-center justify-center text-emerald-500 text-xl border border-emerald-900/50">✓</div>
                 <div className="flex-1">
                    <div className="flex justify-between items-center mb-2">
                       <h4 className="text-sm font-bold text-emerald-400 uppercase">Strong Support</h4>
                       <span className="text-xs text-slate-500 font-sans">PMID: 29845312 (Nature Cell Biology)</span>
                    </div>
                    <p className="text-sm text-slate-300 font-sans mb-3">
                       "Knockdown of beta-catenin in HT-29 cells resulted in a profound shift in the Bax/Bcl-2 ratio within 48 hours, preceding widespread apoptotic markers."
                    </p>
                    <div className="flex gap-2">
                       <span className="px-2 py-0.5 bg-[#050505] border border-slate-800 rounded text-[10px] text-slate-400">Direct Mention</span>
                       <span className="px-2 py-0.5 bg-[#050505] border border-slate-800 rounded text-[10px] text-slate-400">In vitro evidence</span>
                    </div>
                 </div>
              </div>

              {/* Evidence 2 */}
              <div className="bg-[#111] border border-slate-800 p-5 rounded-lg flex gap-4">
                 <div className="w-12 h-12 bg-emerald-950/30 rounded flex items-center justify-center text-emerald-500 text-xl border border-emerald-900/50">✓</div>
                 <div className="flex-1">
                    <div className="flex justify-between items-center mb-2">
                       <h4 className="text-sm font-bold text-emerald-400 uppercase">Supporting Context</h4>
                       <span className="text-xs text-slate-500 font-sans">PMID: 31092844 (Cancer Research)</span>
                    </div>
                    <p className="text-sm text-slate-300 font-sans mb-3">
                       "Survivin downregulation is a known direct consequence of Wnt inhibition, but is generally insufficient alone to trigger terminal apoptosis without secondary Bax activation in CRC models."
                    </p>
                 </div>
              </div>

              {/* Evidence 3 */}
              <div className="bg-[#111] border border-slate-800 p-5 rounded-lg flex gap-4">
                 <div className="w-12 h-12 bg-amber-950/30 rounded flex items-center justify-center text-amber-500 text-xl border border-amber-900/50">⚠</div>
                 <div className="flex-1">
                    <div className="flex justify-between items-center mb-2">
                       <h4 className="text-sm font-bold text-amber-400 uppercase">Conflicting Signal / Nuance</h4>
                       <span className="text-xs text-slate-500 font-sans">PMID: 33419920 (Oncogene)</span>
                    </div>
                    <p className="text-sm text-slate-300 font-sans mb-3">
                       "In a subset of APC-mutant xenografts, direct caspase-3 cleavage was observed independent of Bax status when subjected to high-dose Wnt inhibitor XMD8-92."
                    </p>
                    <div className="p-2 bg-amber-950/20 border border-amber-900/30 rounded text-xs text-amber-300/80 font-sans">
                       <strong>BioReason Resolution:</strong> Acknowledged as a high-dose specific exception, but the synthesized claim holds for physiological or standard therapeutic doses based on consensus.
                    </div>
                 </div>
              </div>

           </div>

        </div>
      </div>
    </div>
  );
}
