"""
Bioquora Founder Bible — Volume XV (Step 15)
Bioquora Innovation, Commercialization & Global Bioeconomy Platform (Codename: BioInnovate)

Implements:
  1. Intellectual Property & Patent Prior Art Index Engine
  2. Technology Readiness Level (TRL 1–9) & Innovation Asset Manager
  3. Freedom-To-Operate (FTO) & Commercial Readiness Evaluator
"""

import uuid
from datetime import datetime, timezone
from typing import List, Optional, Dict, Literal
from pydantic import BaseModel, Field


TRLevel = Literal[
    "TRL_1_BASIC_PRINCIPLES", "TRL_2_CONCEPT_FORMULATED", "TRL_3_PROOF_OF_CONCEPT",
    "TRL_4_LAB_VALIDATION", "TRL_5_PRECLINICAL_VALIDATION", "TRL_6_CLINICAL_PHASE_1",
    "TRL_7_CLINICAL_PHASE_2", "TRL_8_CLINICAL_PHASE_3", "TRL_9_COMMERCIAL_DEPLOYMENT"
]


class PatentRecord(BaseModel):
    """Canonical patent indexed inside the BioInnovate Patent Graph."""
    patent_id: str
    title: str
    assignee_org: str
    claims_concept_urns: List[str]
    expiry_year: int
    is_active: bool = True


class InnovationAsset(BaseModel):
    """Translational biomedical asset tracked in BioInnovate."""
    asset_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    asset_title: str
    lead_researcher_orcid: str
    target_concept_urn: str
    trl_level: TRLevel
    patent_status: Literal["UNPATENTED", "PROVISIONAL_FILED", "PATENT_GRANTED", "LICENSED"]
    estimated_market_size_usd: float


class CommercialReadinessAssessment(BaseModel):
    """Translational readiness assessment generated by BioInnovate Engine."""
    assessment_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    asset_id: uuid.UUID
    asset_title: str
    trl_level: TRLevel
    commercial_readiness_score: float = Field(..., ge=0.0, le=1.0)
    freedom_to_operate_risk: float = Field(..., ge=0.0, le=1.0)
    conflicting_patents: List[str]
    recommended_next_milestone: str


class BioInnovateEngine:
    """
    Production BioInnovate Engine:
      - Indexes patent claims across BioKG target concepts
      - Enrolls and scores translational biomedical assets across TRL 1–9
      - Computes Freedom-To-Operate (FTO) risk and commercial readiness scores
    """

    TRL_NUMERIC_MAP = {
        "TRL_1_BASIC_PRINCIPLES": 0.11,
        "TRL_2_CONCEPT_FORMULATED": 0.22,
        "TRL_3_PROOF_OF_CONCEPT": 0.33,
        "TRL_4_LAB_VALIDATION": 0.44,
        "TRL_5_PRECLINICAL_VALIDATION": 0.55,
        "TRL_6_CLINICAL_PHASE_1": 0.66,
        "TRL_7_CLINICAL_PHASE_2": 0.77,
        "TRL_8_CLINICAL_PHASE_3": 0.88,
        "TRL_9_COMMERCIAL_DEPLOYMENT": 1.00,
    }

    def __init__(self):
        self.patents: Dict[str, PatentRecord] = {}
        self.assets: Dict[uuid.UUID, InnovationAsset] = {}

    def index_patent(
        self,
        patent_id: str,
        title: str,
        assignee: str,
        claim_urns: List[str],
        expiry_year: int = 2042,
    ) -> PatentRecord:
        pat = PatentRecord(
            patent_id=patent_id,
            title=title,
            assignee_org=assignee,
            claims_concept_urns=claim_urns,
            expiry_year=expiry_year,
        )
        self.patents[patent_id] = pat
        return pat

    def register_asset(
        self,
        title: str,
        researcher_orcid: str,
        target_urn: str,
        trl: TRLevel,
        status: Literal["UNPATENTED", "PROVISIONAL_FILED", "PATENT_GRANTED", "LICENSED"],
        market_size_usd: float,
    ) -> InnovationAsset:
        asset = InnovationAsset(
            asset_title=title,
            lead_researcher_orcid=researcher_orcid,
            target_concept_urn=target_urn,
            trl_level=trl,
            patent_status=status,
            estimated_market_size_usd=market_size_usd,
        )
        self.assets[asset.asset_id] = asset
        return asset

    def assess_commercial_readiness(self, asset_id: uuid.UUID) -> Optional[CommercialReadinessAssessment]:
        asset = self.assets.get(asset_id)
        if not asset:
            return None

        # FTO scan across active patents claiming the same target concept URN
        conflicting = []
        current_year = datetime.now(timezone.utc).year
        for p_id, pat in self.patents.items():
            if pat.is_active and pat.expiry_year >= current_year:
                if asset.target_concept_urn in pat.claims_concept_urns:
                    conflicting.append(p_id)

        fto_risk = round(min(1.0, len(conflicting) * 0.35), 4)
        trl_numeric = self.TRL_NUMERIC_MAP.get(asset.trl_level, 0.33)

        # Commercial score combines TRL maturity and low FTO risk
        readiness_score = round(trl_numeric * (1.0 - (0.5 * fto_risk)), 4)

        if asset.trl_level in ["TRL_1_BASIC_PRINCIPLES", "TRL_2_CONCEPT_FORMULATED", "TRL_3_PROOF_OF_CONCEPT"]:
            next_step = "Complete TRL-4 Lab Validation & file provisional patent application."
        elif asset.trl_level in ["TRL_4_LAB_VALIDATION", "TRL_5_PRECLINICAL_VALIDATION"]:
            next_step = "Initiate IND-enabling safety toxicology & prepare Phase 1 clinical trial protocol."
        else:
            next_step = "Engage Technology Transfer Office for biopharma out-licensing or Series A venture spinout."

        return CommercialReadinessAssessment(
            asset_id=asset.asset_id,
            asset_title=asset.asset_title,
            trl_level=asset.trl_level,
            commercial_readiness_score=readiness_score,
            freedom_to_operate_risk=fto_risk,
            conflicting_patents=conflicting,
            recommended_next_milestone=next_step,
        )
