"""
Bioquora Founder Bible — Volume XIII (Step 13)
Bioquora Education Platform (Codename: BioLearn)

Implements:
  1. Grounded Socratic AI Tutor (BioTutor) querying BioKG Mechanistic Pathways
  2. Interactive Virtual Laboratory Simulator (CRISPR Knockout & Cell Viability)
  3. Adaptive Bayesian Knowledge Tracing & Competency Mastery Tracking
"""

import uuid
from datetime import datetime, timezone
from typing import List, Optional, Dict, Literal
from pydantic import BaseModel, Field
from app.knowledge_graph_engine import BioquoraKnowledgeGraphEngine


CompetencyDomain = Literal[
    "MOLECULAR_BIOLOGY", "GENETICS", "CLINICAL_REASONING", "DRUG_DISCOVERY", "BIOMEDICAL_AI"
]


class LearnerMasteryProfile(BaseModel):
    """Dynamic competency mastery profile tracked by BioLearn Knowledge Tracing."""
    learner_id: str
    learner_name: str
    competency_scores: Dict[CompetencyDomain, float] = Field(
        default_factory=lambda: {
            "MOLECULAR_BIOLOGY": 0.50,
            "GENETICS": 0.50,
            "CLINICAL_REASONING": 0.50,
            "DRUG_DISCOVERY": 0.50,
            "BIOMEDICAL_AI": 0.50,
        }
    )
    last_updated: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SocraticQuestion(BaseModel):
    """Citation-grounded Socratic prompt generated by BioTutor."""
    question_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    target_concept_urn: str
    question_text: str
    supporting_kg_path: str
    expected_mechanistic_predicate: str
    scaffolding_hint: str


class VirtualLabExperimentResult(BaseModel):
    """Outcome of an interactive BioLearn virtual laboratory experiment."""
    experiment_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    experiment_type: Literal["CRISPR_KNOCKOUT", "PCR_AMPLIFICATION", "DOCKING_SCREEN"]
    target_gene_urn: str
    simulated_phenotype: str
    viability_percentage: float
    explanation: str


class BioLearnEngine:
    """
    Production BioLearn Engine:
      - Generates adaptive Socratic questions grounded in BioKG topology
      - Simulates virtual laboratory experiments
      - Updates learner competency profiles via Bayesian knowledge tracing
    """

    @staticmethod
    def generate_socratic_prompt(
        source_urn: str,
        target_urn: str,
        kg_engine: BioquoraKnowledgeGraphEngine,
    ) -> SocraticQuestion:
        """Generate a Socratic prompt asking the learner to deduce the mechanistic link."""
        paths = kg_engine.find_mechanistic_paths(source_urn, target_urn, max_hops=3)
        s_node = kg_engine.nodes.get(source_urn)
        t_node = kg_engine.nodes.get(target_urn)
        s_label = s_node.label if s_node else source_urn
        t_label = t_node.label if t_node else target_urn

        if paths:
            path_str = " -> ".join([n.label for n in paths[0].nodes])
            predicate = "MODULATES"
        else:
            path_str = f"{s_label} -> ? -> {t_label}"
            predicate = "ASSOCIATED_WITH"

        return SocraticQuestion(
            target_concept_urn=source_urn,
            question_text=f"Socratic Probe: Based on BioKG mechanistic topology, how does {s_label} influence {t_label} at the cellular level?",
            supporting_kg_path=path_str,
            expected_mechanistic_predicate=predicate,
            scaffolding_hint=f"Consider whether {s_label} acts as an upstream kinase or transcription factor for {t_label}.",
        )

    @staticmethod
    def simulate_virtual_lab_experiment(
        experiment_type: Literal["CRISPR_KNOCKOUT", "PCR_AMPLIFICATION", "DOCKING_SCREEN"],
        target_gene_urn: str,
        kg_engine: BioquoraKnowledgeGraphEngine,
    ) -> VirtualLabExperimentResult:
        """Simulate a CRISPR knockout or assay using BioKG disease dependency edges."""
        node = kg_engine.nodes.get(target_gene_urn)
        label = node.label if node else target_gene_urn

        # Check degree of outgoing CAUSES or TREATS edges to simulate essentiality
        edges = kg_engine.outgoing_edges.get(target_gene_urn, [])
        is_essential = len(edges) > 0

        if experiment_type == "CRISPR_KNOCKOUT":
            viability = 22.5 if is_essential else 88.0
            phenotype = "APOPTOTIC_LETHALITY" if is_essential else "MILD_GROWTH_DELAY"
            explanation = f"CRISPR-Cas9 knockout of {label} resulted in {phenotype} ({viability}% viability) due to disruption of {len(edges)} downstream pathways."
        else:
            viability = 95.0
            phenotype = "SUCCESSFUL_AMPLIFICATION"
            explanation = f"PCR amplification of {label} yielded standard transcript bands."

        return VirtualLabExperimentResult(
            experiment_type=experiment_type,
            target_gene_urn=target_gene_urn,
            simulated_phenotype=phenotype,
            viability_percentage=viability,
            explanation=explanation,
        )

    @staticmethod
    def update_mastery(
        profile: LearnerMasteryProfile,
        domain: CompetencyDomain,
        is_correct: bool,
    ) -> LearnerMasteryProfile:
        """Update learner competency score using simple Bayesian reinforcement."""
        current = profile.competency_scores.get(domain, 0.50)
        delta = 0.08 if is_correct else -0.05
        new_score = max(0.05, min(0.99, current + delta))
        profile.competency_scores[domain] = round(new_score, 4)
        profile.last_updated = datetime.now(timezone.utc)
        return profile
